name: 'Zenodo Upload'
description: 'Uploads release to Zenodo'
inputs:
  token:
    description: 'Zenodo API token'
    required: true
  concept:
    description: 'Concept ID to create new version'
    required: false
  filenames:
    description: 'Files to upload'
    required: false
  metadata:
    description: 'Metadata filename'
    required: false
  sandbox:
    description: 'Use Zenodo sandbox'
    required: false
    default: 'true'
  publish:
    description: 'Publish version'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Zenodo actions
      shell: bash
      env:
        ZENODO_TOKEN: ${{ inputs.token }}
        CONCEPT: ${{ inputs.concept }}
        FILENAMES: ${{ inputs.filenames }}
        METADATA: ${{ inputs.metadata }}
        SANDBOX: ${{ inputs.sandbox }}
        PUBLISH: ${{ inputs.publish }}
      run: python ./src/main.py
