name: 'Zenodo Upload'
description: 'Uploads release artifacts to Zenodo'
inputs:
  token:
    description: 'Zenodo API token'
    required: true
  files:
    description: 'Space-separated list of files to upload'
    required: true
  sandbox:
    description: 'Use Zenodo sandbox'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run Zenodo upload
      run: python ${{ github.action_path }}/zenodo_upload.py
      shell: bash
      env:
        ZENODO_TOKEN: ${{ inputs.token }}
        ZENODO_SANDBOX: ${{ inputs.sandbox }}
        FILES: ${{ inputs.files }}
