name: 'Zenodo Upload'
description: 'Uploads release artifacts to Zenodo'
inputs:
  token:
    description: 'Zenodo API token'
    required: true
  sandbox:
    description: 'Use Zenodo sandbox (true/false)'
    default: 'true'
  repo-owner:
    description: 'GitHub repository owner'
    required: true
  repo-name:
    description: 'GitHub repository name'
    required: true
  base-download-url:
    description: 'Base URL for downloading artifacts'
    default: 'https://github.com'
  citation-path:
    description: 'Path to CITATION.cff file'
    default: 'CITATION.cff'
  artifacts:
    description: 'Comma-separated list of artifacts to upload'
    required: true
runs:
  using: 'composite'
  steps:
    - run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - id: upload
      run: python ${{ github.action_path }}/zenodo_upload.py
      shell: bash