name: 'Zenodo Upload'
description: 'Uploads release artifacts to Zenodo'
inputs:
  token:
    description: 'Zenodo API token'
    required: true
  sandbox:
    description: 'Use Zenodo sandbox (true/false)'
    default: 'true'
runs:
  using: 'composite'
  steps:
    - run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - id: upload
      run: python ${{ github.action_path }}/zenodo_upload.py
      shell: bash
      env:
        ZENODO_SANDBOX: ${{ inputs.sandbox }}
