name: CI/CD
on:
  push:
    tags:
      - 'v*'

env:
  FORCE_COLOR: 1

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          check-latest: true
          python-version: '3.13'

      - name: Install dependencies for zenodo-upload
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r .github/actions/zenodo-upload/requirements.txt

  upload-to-zenodo:
    runs-on: ubuntu-latest
    name: A job to update metadata and push a release to Zenodo

    steps:
      # This step is not needed at the moment but I might decide to add more steps in the future
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Upload to Zenodo
        id: release
        uses: megasanjay/upload-to-zenodo@v2.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          zenodo_token: ${{ secrets.ZENODO_TOKEN }}
          zenodo_deposition_id: SOME_DEPOSITION_ID
          zenodo_publish: true
          zenodo_sandbox: false
          commit_message: 'chore: update ${file_name} for Zenodo release'
          update_metadata_files: true
          codemeta_json: true
          citation_cff: true
          zenodo_json: true

      # Get the doi from the `release` step
      - name: Get the output doi
        run: echo "The released doi was ${{ steps.release.outputs.doi }}"